SELECT di.ID , di.EMAIL , di.FIRST_NAME, di.LAST_NAME
FROM DEVELOPER_INFOS AS di
where 'Python' in (di.SKILL_1,di.SKILL_2,di.SKILL_3)
order by di.ID asc

# SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
# FROM DEVELOPER_INFOS
# WHERE 'Python' IN (SKILL_1,SKILL_2,SKILL3)
# ORDER BY ID